/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyze(text: string, modelPath: string, tokenizerPath: string): SentimentResult

export interface SentimentResult {
  label: string
  score: number
}
